# Github metadata for local build
repository: coderdojoka/Materialien/

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:  pretty

# Setup
title:            "Materialien"
description:  'Materialiensammlung des Coderdojo Karlsruhe. Hier findest du Anleitungen, Aufgaben und Beispiele.'
tagline:      'Materialiensammlung des Coderdojo Karlsruhe'
url:              http://coderdojoka.github.io/Materialien
baseurl:          /
exclude: [alt, Java, Python, Scratch, Vorlagen, LICENSE.md, .gitignore, README.md, Gemfile, Gemfile.lock]
include:  [_assets]

author:
  name:           'Mark Weinreuter'


# Custom vars
version:          0.1.0

# Collections settings
collections_dir: content

# output: true, renders pages within the collection 
# permalink: specifiy directory and file name
collections:
  python:
    output: true
    permalink: /:collection/:path/:title
  scratch:
    output: true
    permalink: /:collection/:path/:title
  arduino:
    output: true
    permalink: /:collection/:path/:title
