print("Hallo! Das ist ein Zaubertrick vileicht brauchst du eine Taschenrechner aber du kanst es auch im Kopf rechnen")
input("Schritt 1:Denk dir eine 3-stellige Zahl mit kleiner werdenden Ziffern (von links nach rechts) und schreibe sie auf(OK = Return).")
input("Schritt 2:Drehe die Zahl, die du aufgeschrieben hast, sodass die neue Zahl größer werdende Ziffern hat(OK = Return).")
input("Schritt 3:Ziehe die Zahl aus Schritt 2 von der Zahl aus Schritt 1 ab(OK = Return).")
input("Schritt 4:Drehe die Zahl, die dabei herausgekommen ist,auch wieder um(OK = Return).")
input("Schritt 5:Rechne die Zahlen aus Schritt 1 und 2 zusammen(OK = Return).")
print("Das Ergebnis ist 1089!!!")